---
- hosts: 172.31.21.231
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install javaopenjdk11
      command: amazon-linux-extras install java-openjdk11 -y 

    - name: getting the repos from jenkins.io
      get_url:
        url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
        dest: "/etc/yum.repos.d/jenkins.repo"


    - name: importing keys from jenkins.io
      ansible.builtin.rpm_key:
       state: present
       key: "https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key"

    - name: installing jenkins
      yum: name=jenkins state=present

    - name: start jenkins
      service: name=jenkins state=restarted
